### ISSUE TITLE
How to configure a Cerberus job ?

### ISSUE THREAD

**Issue by pierre-aurele-martin** [cerberustesting/cerberus-jenkins-plugin#8]
Hello, hello,

I'm trying to launch a Cerberus campaign through Jenkins and I have some issue...

Cerberus is running on Docker - works like a charm.
Jenkins is running on Docker too - works like a charm too.

So the problem must be in the link between those.

Jenkins configuration :
![jenkins_cerberus_conf](https://user-images.githubusercontent.com/3852604/30471581-8cf3b0e8-99f9-11e7-8ad9-ce9255495da1.jpg)

Job configuration :
![jenkins_cerberus_job](https://user-images.githubusercontent.com/3852604/30471593-9e06dd10-99f9-11e7-972d-ba0d603371de.jpg)

Error I got : 
`
Started by user admin
Building in workspace /var/jenkins_home/workspace/Cerberus_test_2
[INFO] [2017-09-13 10:16:46.1646] Launch campaign Jenkins on http://[server-ip]:18081/Cerberus/ with tag -[current_timestamp]
[INFO] [2017-09-13 10:16:46.1646] Campaign is launched successfully. You can follow the report here : http://10.16.3.16:18081/Cerberus//ReportingExecutionByTag.jsp?Tag=-[current_timestamp]
[ERROR] [2017-09-13 10:16:46.1646] error for campaign  Jenkins : 
java.lang.IllegalArgumentException
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:589)
	at org.cerberus.launchcampaign.checkcampaign.CheckCampaignStatus.execute(CheckCampaignStatus.java:88)
	at org.cerberus.jenkinsci.plugins.executecerberustest.ExecuteCerberusCampaign.perform(ExecuteCerberusCampaign.java:142)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)

[ERROR] [2017-09-13 10:16:46.1646] Think to check cerberus log or cerberus queue to resolve problem
[ERROR] [2017-09-13 10:16:46.1646] UNSTABLE
Build step 'Execute Cerberus Campaign' changed build result to FAILURE
Finished: FAILURE
`

I have no log in Cerberus so I don't think it's even receiving instruction from Jenkins.

First thing that bother me is that I've put my login/pwd from Cerberus nowhere in Jenkins parameters so does that mean than Jenkins can access Cerberus without authenticating ? 

Thanks for your help ;)

**Comment by nicodeur** [comment]
Hi @pierre-aurele-martin ,

You're tag is not correct. it would be : `<name_of_execution_tag>-$[current_timestamp]`
where `name_of_execution_tag` is the name you want display to cerberus execution result.

Can you restest with it and repost console result if it's failed again ?

Regards,

Nicolas

**Comment by pierre-aurele-martin** [comment]
Hello @nicodeur 

Thanks for quick reply !

You were right, my tag was incorrect. Thought, I believe it was like that as a default preset...

So now I can see the campaign but have an other error : 

`Bad answer format. Expected 'RunID = ' in the output result. Probably due to bad cerberus_url value. Check server logs `

![jenkins_cerberus_progress](https://user-images.githubusercontent.com/3852604/30474229-389c3d4e-9a03-11e7-8514-96c6a8404c07.png)

Which is strange because the cerberus url is good enough to launch the campaign so I believe I'm missing something.

First time I approach Jenkins so sorry if my problems are due to just misunderstanding the tool...

**Comment by nicodeur** [comment]
@pierre-aurele-martin 

Can you check you're cerberus log to have more detail ? 

I saw you created a Robot name with spaces, may be that the problem comes from there.

**Comment by pierre-aurele-martin** [comment]
@nicodeur 

Progress again cause I've got a log in Cerberus which was not the case with some space char in my robot name 👍 

Thought, there is my log. Robot can not create I think. Robot IP doesn't match the ip of the running Jenkins so might be a problem ?

<img width="898" alt="jenkins_cerberus_progress_2" src="https://user-images.githubusercontent.com/3852604/30475386-f40c299c-9a06-11e7-816a-7dc287f04f55.png">

Thanks a lot !

**Comment by nicodeur** [comment]
This is not this log I want : I want glasfish logs. With docker, you can acess it by cmd `docker logs <container_name>`.

When you execute test by Jenkins, you should have some log added here and retrieve more details on 'Bad error format' error.

**Comment by pierre-aurele-martin** [comment]
Here it is : 

`[#|2017-09-15T09:08:55.085+0000|INFO|glassfish 4.1||_ThreadID=914;_ThreadName=Thread-8;_TimeMillis=1505466535085;_LevelValue=800;|
  2017-09-15 09:08:55 WARN  ExecutionQueueWorkerThread:251 - Bad answer format: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>GlassFish Server Open Source Edition  4.1  - Error report</title><style type="text/css"></style> </head><body><h1>HTTP Status 404 - Not Found</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Not Found</p><p><b>description</b>The requested resource is not available.</p><hr/><h3>GlassFish Server Open Source Edition  4.1 </h3></body></html>|#]

[#|2017-09-15T09:08:55.087+0000|INFO|glassfish 4.1||_ThreadID=914;_ThreadName=Thread-8;_TimeMillis=1505466535087;_LevelValue=800;|
  2017-09-15 09:08:55 WARN  ExecutionQueueWorkerThread:179 - Execution in queue 3 has finished with error
org.cerberus.engine.threadpool.impl.ExecutionQueueWorkerThread$RunQueueProcessException: Bad answer format. Expected 'RunID = ' in the output result. Probably due to bad cerberus_url value. Check server logs
	at org.cerberus.engine.threadpool.impl.ExecutionQueueWorkerThread.runParseAnswer(ExecutionQueueWorkerThread.java:252)
	at org.cerberus.engine.threadpool.impl.ExecutionQueueWorkerThread.run(ExecutionQueueWorkerThread.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)|#]
`

Thanks for your help

**Comment by vertigo17** [comment]
404 means that the cerberus_url parameter is not defined correct.
Take the parameter and open it from Cerberus itself in order to confirm you see the login page.
http://cerberusHost:Port/Cerberus
if you add /RunTestCase (http://cerberusHost:Port/Cerberus/RunTestCase) to the URL you should see an error message from the public execution servlet.

Please confirm the parameter value.

**Comment by nicodeur** [comment]
Hi @pierre-aurele-martin

Did you resolved your problem ?

Regards
